name: Master Branch

on:
  pull_request:
    types: [closed, review_requested]
    branches:
      - "master"
      - "develop"




jobs:
  test_cito:
    name: Test Cito
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Maven Package
        working-directory: cito
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        working-directory: cito
        run: mvn -B clean verify

  test_client:
    name: Test Client
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Maven Package
        working-directory: client
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        working-directory: client
        run: mvn -B clean verify

  sonar_cito:
    name: Test - SonarCloud Scan Cito
    runs-on: ubuntu-18.04
    needs: [test_client, test_cito]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: SonarCloud Scan
        working-directory: cito
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar_client:
    name: Test - SonarCloud Scan Client
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: SonarCloud Scan
        working-directory: client
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  heroku_cito_engine:
    name: Deploy to heroku cito-engine
    runs-on: ubuntu-18.04
    needs: sonar_client
    steps:
      - name: Check out repository
        working-directory: cito
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        working-directory: cito
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cito-engine"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  heroku_cito_client:
    name: Deploy to heroku cito-client
    runs-on: ubuntu-18.04
    needs: sonar_client
    steps:
      - name: Check out repository
        working-directory: client
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        working-directory: client
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cito-client"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  heroku_cito_web:
    name: Deploy to heroku cito-web
    runs-on: ubuntu-18.04
    needs: sonar_client
    steps:
      - name: Check out repository
        working-directory: frontend
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        working-directory: frontend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cito-web"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
